/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Artist {
  'id' : string,
  'name' : string,
  'imageUrl' : string,
  'genre' : string,
}
export interface Event {
  'country' : string,
  'venue' : string,
  'city' : string,
  'artistId' : string,
  'eventTitle' : string,
  'sourceLabel' : string,
  'eventUrl' : string,
  'dateTime' : Time,
}
export type Result = { 'alreadyExists' : null } |
  { 'eventNotFound' : string } |
  { 'notFound' : null } |
  { 'success' : null } |
  { 'unauthorized' : null };
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addEventToRadar' : ActorMethod<[string], Result>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllEvents' : ActorMethod<[], Array<Event>>,
  'getArtist' : ActorMethod<[string], [] | [Artist]>,
  'getArtists' : ActorMethod<[], Array<Artist>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getEventsByArtist' : ActorMethod<[string], Array<Event>>,
  'getMyRadarSummary' : ActorMethod<[Principal], [bigint, bigint]>,
  'getRadarEvents' : ActorMethod<[], Array<Event>>,
  'getTrackedArtistEvents' : ActorMethod<[Principal], Array<Event>>,
  'getTrackedArtists' : ActorMethod<[Principal], Array<string>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeSeedData' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeEventFromRadar' : ActorMethod<[string], Result>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'toggleTrackedArtist' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];