/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Result = IDL.Variant({
  'alreadyExists' : IDL.Null,
  'eventNotFound' : IDL.Null,
  'notFound' : IDL.Null,
  'success' : IDL.Null,
  'unauthorized' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const Event = IDL.Record({
  'country' : IDL.Text,
  'venue' : IDL.Text,
  'city' : IDL.Text,
  'artistId' : IDL.Text,
  'eventTitle' : IDL.Text,
  'sourceLabel' : IDL.Text,
  'eventUrl' : IDL.Text,
  'dateTime' : Time,
});
export const Artist = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'imageUrl' : IDL.Text,
  'genre' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addEventToRadar' : IDL.Func([IDL.Text], [Result], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
  'getArtist' : IDL.Func([IDL.Text], [IDL.Opt(Artist)], ['query']),
  'getArtists' : IDL.Func([], [IDL.Vec(Artist)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEventsByArtist' : IDL.Func([IDL.Text], [IDL.Vec(Event)], ['query']),
  'getMyRadarSummary' : IDL.Func(
      [IDL.Principal],
      [IDL.Nat, IDL.Nat],
      ['query'],
    ),
  'getRadarEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
  'getTrackedArtistEvents' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Event)],
      ['query'],
    ),
  'getTrackedArtists' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeSeedData' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeEventFromRadar' : IDL.Func([IDL.Text], [Result], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'toggleTrackedArtist' : IDL.Func([IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Result = IDL.Variant({
    'alreadyExists' : IDL.Null,
    'eventNotFound' : IDL.Null,
    'notFound' : IDL.Null,
    'success' : IDL.Null,
    'unauthorized' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const Event = IDL.Record({
    'country' : IDL.Text,
    'venue' : IDL.Text,
    'city' : IDL.Text,
    'artistId' : IDL.Text,
    'eventTitle' : IDL.Text,
    'sourceLabel' : IDL.Text,
    'eventUrl' : IDL.Text,
    'dateTime' : Time,
  });
  const Artist = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'imageUrl' : IDL.Text,
    'genre' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addEventToRadar' : IDL.Func([IDL.Text], [Result], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
    'getArtist' : IDL.Func([IDL.Text], [IDL.Opt(Artist)], ['query']),
    'getArtists' : IDL.Func([], [IDL.Vec(Artist)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEventsByArtist' : IDL.Func([IDL.Text], [IDL.Vec(Event)], ['query']),
    'getMyRadarSummary' : IDL.Func(
        [IDL.Principal],
        [IDL.Nat, IDL.Nat],
        ['query'],
      ),
    'getRadarEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
    'getTrackedArtistEvents' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Event)],
        ['query'],
      ),
    'getTrackedArtists' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeSeedData' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeEventFromRadar' : IDL.Func([IDL.Text], [Result], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'toggleTrackedArtist' : IDL.Func([IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };